# Config file for automatic testing at travis-ci.org

language: python
python:
    - 3.8
    - 3.7
    - 3.6

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
            key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
            - clang-9

env:
    - ALLOWFAIL=yes
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U tox-travis
    - pip install coverage
    - pip install codecov

jobs:
    allow_failures:
        -   if: branch = V1.4.0_unstable
            env: ALLOWFAIL=yes

# Command to run tests, e.g. python setup.py test
script:
  - tox


after_script:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
