# Config file for automatic testing at travis-ci.org

language: python
python:
    - 3.8
    - 3.7
    - 3.6

env:
    - ALLOWFAIL=yes
# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U tox-travis
    - pip install coverage
    - pip install codecov

jobs:
    allow_failures:
        -   if: branch = V1.4.0_unstable
            env: ALLOWFAIL=yes

# Command to run tests, e.g. python setup.py test
script:
  - tox


after_script:
  - codecov
  - bash <(curl -s https://codecov.io/bash)
