name: Build CI

on: [ push ]

jobs:
    build:

        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest ]
                python-version: [ 3.7, 3.8 ]

        steps:
            -   uses: actions/checkout@v2
            -   name: Setup Graphviz
                uses: ts-graphviz/setup-graphviz@v1
            -   name: Install LLVM and Clang
                uses: KyleMayes/install-llvm-action@v1
                with:
                    version: "9.0"
                    directory: ${{ runner.temp }}/llvm
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install coverage coveralls pytest
                    pip install .
            -   name: Test with pytest
                run: |
                    coverage run --source=rnalysis/ -m pytest tests/
                continue-on-error: false
            -   name: Coveralls
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: |
                    coverage report -m
                    coveralls --service=github
                continue-on-error: true
